
detectron2:
  config_file: "detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
  confidence_threshold: 0.5
  opts: 
    - "MODEL.WEIGHTS"
    - "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"
